# Generated by Django 5.2.13 on 2026-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireevent',
            name='event_type',
            field=models.CharField(choices=[('fire', 'Fire'), ('smoke', 'Smoke')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
